config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get  :kid_signup, on: :collection
    post :kid_signup, on: :collection
    get  :parent_signup, on: :collection
    post :parent_signup, on: :collection
    get  :login, on: :collection
    post :login, on: :collection
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  validates :username,
    presence: true,
    uniqueness: true,
    length: { minimum: 3, max: 30 }

  validates :password,
    presence: true,
    length: { minimum: 8, max: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # http://liamkaufman.com/blog/2013/02/27/adding-real-time-to-a-restful-rails-app/
  # https://github.com/ankane/searchkick

  def index
    @users = User.all
    # render 'layouts/application'
  end

  def login
  end

  def show
    @user = User.find(params[:id])
  end

  def signup
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.save
    redirect_to @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.update(user_params)
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end


  private
    def user_params
      params.require(:users).permit(
        :user, :password, :age, :email, :picture_url, :gender, :status
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wechitchat" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to users_index_path, class: 'navbar-brand' do %>
          <%= image_tag('logo.png', height: '50', width: '225') %>
        <% end %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav pull-right">
            <li class="<%= 'active' if current_page?(users_index_path) %>"><%= link_to "Home", users_index_path, class: 'active' %></li>
            <li class="<%= 'active' if current_page?(login_users_path) %>"><%= link_to "Login", login_users_path %></li>
            <li class="<%= 'active' if current_page?(kid_signup_users_path) || current_page?(parent_signup_users_path) %>">
              <%= link_to "SignUp", kid_signup_users_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class=<%= content_for?(:side_bar) ? "col-lg-9" : "col-lg-12" %>>
          <%= bootstrap_flash %>
          <div class="well content">
            <%= yield %>
          </div>
        </div>
        <%= yield(:side_bar) if content_for?(:side_bar) %>
      </div>
    </div>

    <footer>
      <p class="container">&copy; <%= Time.now.year %> Wechitchat</p>
    </footer>

  </body>
</html>

app/views/users/index.html.haml
- content_for :title do
  Home

- content_for :side_bar do
  .col-lg-3
    .well.sidebar-nav
      %h3.text-center Login
      .sidebar
        = simple_form_for :user, url: login_users_path, html: { class: 'form-horizontal' } do |f|
          = f.input :user
          = f.input :password
          = f.button :submit, 'Login', class: 'side-bar-button'

    .well.sidebar-nav
      %h3.text-center SignUp
      .signup-sidebar
        %p.text-center= link_to '... for Kids!', kid_signup_users_path
        %p.text-center= link_to '... for Parents!', parent_signup_users_path

%h3 Chatting Safe With WeChitChat
WeChitChat is devoted to keeping WeChitChat a safe environment for kids.
Kids, have you ever wanted to chat with other kids, but your parents told you it wouldn't be safe?
They are right, the internet can be a dangerous place, that is why WeChitChat is here.
We have made a secure and safe place for children to chat in. Parents, we have a place for you too.
To make an account, just go to the sign up page->parent sign up to make an account so you can monitor what your child is doing.

%h3 A brief introduction of WeChitChat
To make a WeChitChat account, look at the side of the page and look for sign up or go to the sign up.
WeChitChat is a safe and secure place for your kids to chat because we filter out foul language and allow parental controls.
Look in about us for more information on creating an account on WeChitChat, and to find out more about WeChitChat.

%h3 About Us
WeChitChat is a safe place for kids to chat with their friends, and is completely free.
We help provide a safe environment for your child by blocking bad words, monitoring, and allow parental controls.
WeChitChat is happily brought to you by Aaron Barlow who is 14.  I built this site in 7 months, spending 4 hours a day, to make it one of the safest places for kids to chat.
%br
%br
What you can do on Wechitchat:
%ul
  %li Create an account
  %ul
    %li Your account name is your alias in WeChitChat
    %li Write something about yourself for your profile
  %li Allows messaging between two friends
  %ul
    %li Instand online chatting
    %li Video Chatting
    %li Post messages on your profile and friend's profile
    %li Add or delete friends
For parents:
%ul
  %li Can create a parent account linked to their child's account
  %ul
    %li Can monitor child's profile and messaging activity
    %li Can delete child's messages, posts and friends

app/views/users/kid_signup.html.haml
- content_for :title do
  SignUp

- content_for :side_bar do
  .col-lg-3
    .well.sidebar-nav.center
      %h3 Why Sign Up for a child's account?
      %ul.nav.nav-list
        We provide safe chatting, messaging, parental monitoring,
        admin monitoring and bad word blocking filter.
        %li= link_to 'Are you a Parent? SignUp here!', parent_signup_users_path


%h1 SignUp

= simple_form_for :user, url: kid_signup_users_path, html: { class: 'form-horizontal proper-width' } do |f|
  = f.input :user
  .hint Use 3-15 alphanumeric characters: a-z, 0-9, no spaces. Please do not use your name or any other information that identifies you in real life.
  = f.input :password
  .hint Your email will only be used for retrieving your password and for important information concerning your safety. Only your friends will be able to see it. 
  = f.input :password_confirmation
  = f.button :submit, 'Login', class: 'side-bar-button'

app/views/users/login.html.haml
- content_for :title do
  Login


- content_for :side_bar do
  .col-lg-3
    .well.sidebar-nav.center
      %h3 Trouble Logging In?
      Are you having trouble logging into your account?
      There are two possibilities:
      %br
      %br
      %ol
        %li That account does not exist
        %li You forgot your account login
      %a{:href => "get_pass.php"} Retrieve Lost Account


%h1 Login

= simple_form_for :user, url: login_users_path, html: { class: 'form-horizontal proper-width' } do |f|
  = f.input :user
  = f.input :password
  = f.button :submit, 'Login', class: 'side-bar-button'

%br
%br
%p=link_to "Don't have an account? Sign up!", kid_signup_users_path

app/views/users/parent_signup.html.haml
- content_for :title do
  SignUp

- content_for :side_bar do
  .col-lg-3
    .well.sidebar-nav.center
      %h3 Why Sign Up for a child's account?
      %ul.nav.nav-list
        We provide safe chatting, messaging, parental monitoring,
        admin monitoring and bad word blocking filter.
        %li= link_to 'Are you a Parent? SignUp here!', parent_signup_users_path


%h1 SignUp

= simple_form_for :user, url: parent_signup_users_path, html: { class: 'form-horizontal proper-width' } do |f|
  = f.input :user
  .hint Use 3-15 alphanumeric characters: a-z, 0-9, no spaces. Please do not use your name or any other information that identifies you in real life.
  = f.input :password
  .hint Your email will only be used for retrieving your password and for important information concerning your safety. Only your friends will be able to see it.
  = f.input :password_confirmation
  = f.button :submit, 'Login', class: 'side-bar-button'